# Base image
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /

# Copy files into container
COPY MainScores.py .
COPY scores.txt /Scores.txt

# Copy requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


# Expose port
EXPOSE 5000

# Set the command to run the Flask app
CMD ["python", "MainScores.py"]
